AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  BucketNameParameter:
    Description: S3 Bucket Name
    Type: String
    Default: mh-lab121-nested

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketNameParameter
    DeletionPolicy: Delete
  
