version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo 'Installing aws tools'
      - pip3 install awscli --upgrade --user
  build:
    commands:
      - echo Validating template...
      - aws cloudformation validate-template --template-body bucket.yaml
