version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo Checking template health...
      - aws cloudformation describe-stacks --stack-name $STACK_NAME --query Stacks[].StackStatus
